// src/quotes.js
export const quotes = [
    "Do not wait to strike till the iron is hot, but make it hot by striking.",
    "Great minds discuss ideas; average minds discuss events; small minds discuss people.",
    "Whether you think you can or think you can’t, you’re right.",
    "The best way to predict the future is to invent it.",
    "I have not failed. I’ve just found 10,000 ways that won’t work.",
    "Success is not the key to happiness. Happiness is the key to success.",
    "Believe you can and you’re halfway there.",
    "It does not matter how slowly you go as long as you do not stop.",
    "Your time is limited, so don’t waste it living someone else’s life.",
    "The only way to do great work is to love what you do.",
    "If you are not willing to risk the usual, you will have to settle for the ordinary.",
    "Success usually comes to those who are too busy to be looking for it.",
    "Don’t be afraid to give up the good to go for the great.",
    "I find that the harder I work, the more luck I seem to have.",
    "Opportunities don't happen. You create them.",
    "The only limit to our realization of tomorrow is our doubts of today.",
    "Don’t let yesterday take up too much of today.",
    "You learn more from failure than from success. Don’t let it stop you. Failure builds character.",
    "It’s not whether you get knocked down, it’s whether you get up.",
    "People who are crazy enough to think they can change the world, are the ones who do.",
    "We may encounter many defeats but we must not be defeated.",
    "Knowing is not enough; we must apply. Wishing is not enough; we must do.",
    "Imagine your life is perfect in every respect; what would it look like?",
    "Security is mostly a superstition. Life is either a daring adventure or nothing.",
    "The man who has confidence in himself gains the confidence of others.",
    "The only place where success comes before work is in the dictionary.",
    "The best time to plant a tree was 20 years ago. The second best time is now.",
    "It’s hard to beat a person who never gives up.",
    "Everything you’ve ever wanted is on the other side of fear.",
    "In order to succeed, we must first believe that we can.",
    "The only way to achieve the impossible is to believe it is possible.",
    "You don’t have to be great to start, but you have to start to be great.",
    "I attribute my success to this: I never gave or took any excuse.",
    "The future belongs to those who believe in the beauty of their dreams.",
    "You are never too old to set another goal or to dream a new dream.",
    "Dream big and dare to fail.",
    "Act as if what you do makes a difference. It does.",
    "What you get by achieving your goals is not as important as what you become by achieving your goals.",
    "Don’t watch the clock; do what it does. Keep going.",
    "You don’t have to see the whole staircase, just take the first step.",
    "Keep your face always toward the sunshine—and shadows will fall behind you.",
    "The only way to do great work is to love what you do.",
    "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle.",
    "Your limitation—it’s only your imagination.",
    "Push yourself, because no one else is going to do it for you.",
    "Sometimes later becomes never. Do it now.",
    "Great things never come from comfort zones.",
    "Dream it. Wish it. Do it.",
    "Success doesn’t just find you. You have to go out and get it."
  ];
  